#+TITLE: Server Configuration - From nothing to a fully functioning server
#+AUTHOR: Harry Henry Gebel
#+EMAIL: harry@gebel.tech
#+DATE: <2020-08-02 Sun>
#+EXPORT_FILE_NAME: README
#+LANGUAGE: en
#+PROPERTY: header-args :exports code

* About this document
This document is an opinionated description of how to set up a server
from scratch, including the reasons for certain decisions. It is
intended primarily for the author's own benefit, both as a writing
exercise and as a reference, but is made available on a public
repository in the hope that others may find it useful, or at least
educational or exasperating. It assumes the user knows how to use ssh
and has already generated a ssh key pair for logins[fn::Users of
Github may have already set up a ssh key pair, and may safely use the
same key pair they use to interact with their github repositories to
log into any servers they create], and that the user already possesses
at least a rudimentary knowledge of working from the command line and
has their local system set up with a Unix compatible shell if it does
not come with one (Windows[fn::Some examples of Windows projects that
include Unix compatible shells are Git for Windows (Gitbash), the
Windows Subsystem for Linux, Cygwin, and MinGW. There are other
options as well, these are the ones the author is aware of. PuTTY is
also available for Windows as an option to use ssh without having a
Unix compatible shell installed on the local
system.]). Patches[fn::Please submit any patches or pull requests
against the source file =server-configuration.org=, not against
generated files such as =README.md=] or suggestions for improvement,
especially regarding security or best practices, are welcome at all
times, as are differing opinions.

This document is released into the public domain where legally
permissible, and all rights are permanently and irrevocably waived, to
the extent permitted by law.

* Acquiring a domain name
Traffic over the internet is routed to numeric addresses known as IP
address which function similarly to phone numbers. These addresses are
difficult to remember, and so the DNS[fn::Domain Name System] service
was created to allow them to be looked up by name. DNS provides
various types of records that allow you to look up an IP address from
a domain name, find the services such as the mail server for a domain,
redirect certain names to other names, lookup information about a
domain, and lookup domain names from IP addresses. Purchasing,
or more accurately leasing[fn::Domains are public resources, and can
only be leased not owned], your own domain name gives you complete
control of the domain on a yearly basis and, if you wish to host your
own email server, will help greatly in making emails originating from
your domain get the highest trust ratings, preventing emails you send
from being marked as spam or rejected outright.

Another option is to obtain a free name from one of several
sources. These names are subdomains to the domains the free domain
provider owns, and therefore lack some of the name recognition or
branding that can be associated with your own domain. However, they
also lack the yearly costs of purchasing a domain name of your
own. For reasons that will be gone into later, email sent from these
domains will be rejected as spam by many receivers. This is not a
concern if you choose not to host email from your domain, which in any
case is probably not recommended for a free domain.

** A brief introduction to the Domain Name Service

** Registering your own domain name

** Obtaining a free domain name.

** Static and dynamic IP addresses

* Acquiring a Debian server

** DigitalOcean

** Google Cloud Platform
Google Compute Platform (GCP) provides a singe free Debian[fn::Like
Digital Ocean there are many other options as well.] server to any
user with a Google account.

The hardware specifications for this free server are essentially equal
to the resources of the $5/month server from Digital Ocean, but the
bandwidth limitation is much lower[fn::1GB/month for a free GCP
server, versus 1TB/month for a $5 server from DigitalOcean. On the
other hand, Google only charges for outgoing traffic, while
DigitalOcean charges for both incoming and outgoing, which makes it
attractive for use cases that require significantly more incoming than
outgoing bandwidth]. Owing to the extreme speeds available from
Google's network, bandwidth from Google is generally more expensive
than other providers. While the bandwidth limitations place some
restrictions on the use of the server, it can still be useful for
learning purposes or to provide simple backup services to a server on
another network. Setting up a server using GCP is outside of the scope
of this document, but is similar in many ways to Digital Ocean and
Google provides copious documentation.

* Getting started
These steps are necessary to get from a fresh, unconfigured server to one
that can be securely logged into and left running.

** Etckeeper
Etckeeper is the first package to install, it will create a git
repository that will control all changes made in the /etc directory.

** fish

** sudo
*** The editor variable

** SSH server setup

** NTP server setup
#+BEGIN_QUOTE
The man with one watch knows what time it is. The man with two watches
is never sure. --- Segal's law
#+END_QUOTE

Many internet services depend on the clocks on both sides of a
connection to being accurate. The NTP[fn::Network Time Protocol]
service synchronizes the system clock to UTC[fn::Coordinated Universal
Time. UTC is the time zone of London, United Kingdom, but does not
have daylight savings time. It is essentially similar to Greenwich
Mean Time, one major difference being that in GMT, owing to its use in
astronomy and navigation, the day starts at noon, while in UTC the day
starts at midnight. Consequently, while the time will normally be
identical in UTC and GMT, the date will be different between midnight
and noon.] to a high degree of accuracy with minimal configuration. If
a server exists on a permanent, publicly accessible IP address, it can
optionally be set up to give back to the internet time community by
becoming part of the pool of public time servers.

Debian servers come with their local time set to UTC, and should
generally be left with UTC set as their local timezone. In this way,
logs can easily be compared even though the servers are physically
located in different time zones than the administrator or other
managed servers. UTC is the standard time zone of the internet, and
has many advantages over local time including being at all times the
same at all locations worldwide, and it lacks daylight savings time which
renders questions involving time calculations across the jump between
standard time and daylight savings time moot.

*** NTP service - sync time only
Debian comes configured to automatically keep it's clock synced to the
current time using the existing NTP network. No additional
configuration is necessary. Systems which do not function as pool
servers do not require their time to be as accurate as those that do,
therefore systems that are configured only as a client of the NTP
network can safely be operated with a single time source, as if the
source is lost the default configuration can usually correct for clock
drift sufficiently until the source becomes available again.

*** NTP service - join the pool of public NTP servers
The NTP network is organized into a series of layers called
stratum. Stratum 0 are the hyper accurate time sources that are the
source for the time provided by all other stratum. Sources in stratum
0 include the various satellite positioning networks, radio clocks
such as those provide by the NIST[fn:: The United States National
Institute of Standards and Technology, formerly known as the National
Bureau of Standards], or atomic clocks that may be available if the
server is located at a facility that has such a thing. These sources
are also know as reference clocks, and are the ultimate source of time
not just for the NTP network, but for most time used all over the
world.

Stratum 1 servers synchronize their time directly from a reference clock.

Stratum 2 servers synchronize their time by tracking several stratum 1
servers. Several stratum 1 sources are necessary to correct for
stratum 1 servers that may be inoperative, malfunctioning, or
temporarily out of sync.

Stratum 3 servers synchronize their time by tracking several stratum 2
servers. Like stratum 2 servers they require several sources to
maintain accuracy. The ideal number to track must balance the need of
the stratum 3 server to provide an accurate time with the need of the
stratum 2 servers, which suffer extremely heavy traffic, to avoid
being overwhelmed. The worst case number is 2, since there is no way
to determine which is likely to be correct if they disagree. The ideal
number is generally acknowledged as being between 5 and 7. A server
that has fewer than five sources risks losing enough sources that it
is left with two. A server that exceeds seven sources puts far too
much load on the network.

Additional stratum proceed along the same plan up until
stratum 14. Pool servers should be located at stratum 3 or 4.


*** Checking the status of the NTP service

** Unattended upgrades setup
You may wish to delay this until you have email set up, but in any
case should not delay longer than necessary.


* Email server

** Full email service
This will configure the server to manage all email for a domain,
including securely sending email both with local origin and through a
remote client such as Thunderbird or K-9 Mail, receiving emails sent
from other domains, and providing IMAP services to remote clients.

*** Implement encrypted passwords in Dovecot / Postfix

** Local/forwarded email
This will configure the server to direct locally originating emails
(emails sent from various server administrative tools) to be stored in
a local mailbox or forwarded to the server handling mail for the domain.
