#+TITLE: Server Configuration - From nothing to a fully functioning server
#+AUTHOR: Harry Henry Gebel
#+EMAIL: harry@gebel.tech
#+DATE: <2020-08-02 Sun>
#+LANGUAGE: en

* Acquiring a domain name

** Registering your own domain name

** Using a free domain name service

* Acquiring a Debian server

** Digital Ocean

** Google Compute Cloud

* Getting started
These steps are necessary to get from a fresh, unconfigured server to one
that can be securely logged into and left running.

** Etckeeper
Etckeeper is the first package to install, it will create a git
repository that will control all changes made in the /etc directory.

** SSH server setup

** NTP server setup
#+BEGIN_QUOTE
The man with one watch knows what time it is. The man with two watches
is never sure. --- Segal's law
#+END_QUOTE

Many internet services depend on the clocks on both sides of a
connection to be set accurately. The NTP [fn::Network Time Protocol]
service allows this to be done with a high degree of accuracy with
minimal configuration. If a server exists on a permanent, publicly
accessible IP address, it can optionally be set up to give back to the
internet time community by becoming part of the pool of public time
servers.

Servers should generally be left using UTC as their local timezone. In
this way, logs can easily be compared even though the servers are
physically located in different time zones that the administrator or
other managed servers. UTC is the standard time of the internet.

*** NTP service - sync time only
Debian comes configured to automatically keep it's clock synced to the
current time using the existing NTP network. No additional
configuration is necessary. Systems that are configured only as a
client of the NTP network can safely be operated with a single time
source, as if the source is lost the default configuration can usually
correct for clock drift sufficiently until the source becomes available again.

*** NTP service - join the pool of public NTP servers
The NTP network is organized into a series of layers called
stratum. Stratum 0 are the hyper accurate time sources that are the
source for the time provided by all other stratum. Sources in stratum
0 include the various satellite positioning networks, radio clocks
such as those provide by the NIST [fn:: The United States National
Institute of Standards and Technology], or atomic clocks that may be
available if the server is located at a facility that has such a
thing. These sources are also know as reference clocks, and are the
ultimate source of time not just for the NTP network, but for most
time used all over the world.

Stratum 1 servers synchronize their time directly from a reference clock.

Stratum 2 servers synchronize their time by tracking several stratum 1
servers. Several stratum 1 sources are necessary to correct for
stratum 1 servers that may be inoperative, malfunctioning, or
temporarily out of sync.

Stratum 3 servers synchronize their time by tracking several stratum 2
servers. Like stratum 2 servers they require several sources to
maintain accuracy. The ideal number to track must balance the need of
the stratum 3 server to provide an accurate time with the need of the
stratum 2 servers, which suffer extremely heavy traffic, to avoid
being overwhelmed. The worst case number is 2, since there is no way
to determine which is likely to be correct if they disagree. The ideal
number is generally acknowledged as being between 5 and 7. A server
that has fewer than five sources risks losing enough sources that it
is left with two. A server that exceeds seven sources puts far too
much load on the network.

Additional stratum proceed along the same plan up until
stratum 14. Pool servers should be located at stratum 3 or 4.


*** Checking the status of the NTP service

** Unattended upgrades setup
You may wish to delay this until you have email set up, but in any
case should not delay longer than necessary.


* Email server

** Full email service
This will configure the server to manage all email for a domain,
including securely sending email both with local origin and through a
remote client such as Thunderbird or K-9 Mail, receiving emails sent
from other domains, and providing IMAP services to remote clients.

*** TODO Implement encrypted passwords in Dovecot / Postfix

** TODO Local/forwarded email
This will configure the server to direct locally originating emails
(emails sent from various server administrative tools) to be stored in
a local mailbox or forwarded to the server handling mail for the domain.
